INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Wanda', 'Samudio', 'wsamudio0@wp.com', 'Město Albrechtice');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Yard', 'Baptiste', 'ybaptiste1@hostgator.com', 'Outeiro Seco');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Gae', 'Bradbrook', 'gbradbrook2@freewebs.com', 'Carlos Casares');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Shoshana', 'Okill', 'sokill3@deviantart.com', 'Jiangcun');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Minne', 'Canete', 'mcanete4@mlb.com', 'Mboursou Léré');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Estell', 'Illston', 'eillston5@joomla.org', 'Barat');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Minta', 'Deeson', 'mdeeson6@rakuten.co.jp', 'Meixi');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Shepherd', 'Cotelard', 'scotelard7@sina.com.cn', 'Bentengjawa');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Katey', 'Lackie', 'klackie8@noaa.gov', 'Ambatolampy');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Alick', 'Ackrill', 'aackrill9@shinystat.com', 'Agpangi');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Bari', 'Gildroy', 'bgildroya@epa.gov', 'Omoku');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Sissie', 'Fakes', 'sfakesb@tripadvisor.com', 'Pulo');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Arleyne', 'Rosier', 'arosierc@tinyurl.com', 'Igarapé');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Selia', 'Kidwell', 'skidwelld@mail.ru', 'Aksu');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Buddie', 'Agates', 'bagatese@sina.com.cn', 'Udi');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Braden', 'Jiles', 'bjilesf@icq.com', 'Lovran');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Nicol', 'Lanchberry', 'nlanchberryg@google.com.hk', 'Conima');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Jeanelle', 'Tindley', 'jtindleyh@desdev.cn', 'Křenovice');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Sarita', 'Darrington', 'sdarringtoni@addthis.com', 'Barrie');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Archaimbaud', 'Simek', 'asimekj@umn.edu', 'Dallas');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Lexis', 'Orniz', 'lornizk@woothemes.com', 'Assiniboia');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Foster', 'Lente', 'flentel@oaic.gov.au', 'Pogonsili');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Chuck', 'Canepe', 'ccanepem@wikipedia.org', 'Lizhuangzi');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Berni', 'Simunek', 'bsimunekn@sohu.com', 'Khon Kaen');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Templeton', 'Ragborne', 'tragborneo@mapquest.com', 'Viline');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Sim', 'Nafzger', 'snafzgerp@wordpress.org', 'Łobodno');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Henrie', 'Castiblanco', 'hcastiblancoq@omniture.com', 'Ya’erya');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Hewe', 'Heis', 'hheisr@surveymonkey.com', 'Kostopil’');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Fraze', 'Sauvan', 'fsauvans@ted.com', 'Omutninsk');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Kaitlynn', 'Yurkin', 'kyurkint@rambler.ru', 'Geneng');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Matti', 'Heigho', 'mheighou@time.com', 'Zykovo');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Milicent', 'Swede', 'mswedev@state.gov', 'Birmingham');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Malia', 'Goldwater', 'mgoldwaterw@fotki.com', 'Atakpamé');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Piotr', 'Shills', 'pshillsx@altervista.org', 'Barengkok');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Ingemar', 'Firmin', 'ifirminy@chronoengine.com', 'Florencia');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Gwenneth', 'Pfaffe', 'gpfaffez@state.gov', 'North York');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Keriann', 'Sexty', 'ksexty10@zdnet.com', 'Al Bāţinah');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Tawsha', 'Skillitt', 'tskillitt11@reference.com', 'Kosikha');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Cosette', 'Etteridge', 'cetteridge12@qq.com', 'Shahr-e Şafā');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Adrien', 'Gatesman', 'agatesman13@bloglovin.com', 'Shuyuan');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Fannie', 'Ladbury', 'fladbury14@imageshack.us', 'Jiling');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Vassili', 'Sturmey', 'vsturmey15@phpbb.com', 'Vnorovy');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Rolph', 'Layus', 'rlayus16@ftc.gov', 'Fangxi');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Skell', 'Packham', 'spackham17@gnu.org', 'Králův Dvůr');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Kelli', 'Font', 'kfont18@tmall.com', 'Huangdu');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Phyllis', 'Wiggam', 'pwiggam19@jiathis.com', 'Roriz');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Halsy', 'Colquite', 'hcolquite1a@prlog.org', 'Yuanqiao');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Dianemarie', 'Arnaud', 'darnaud1b@delicious.com', 'Chita');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Sterne', 'Looker', 'slooker1c@ed.gov', 'Ntobo');
INSERT INTO Customers (first_name, last_name, email, customer_location) VALUES ('Allegra', 'Prestwich', 'aprestwich1d@aboutads.info', 'Leles');
